### ISSUE TITLE
Creating a redirect on live site gives "Integrity constraint violation" error

### ISSUE THREAD

**Issue by arentsen** [barrelstrength/sprout#339]
### Description

The plugin works locally, but on the live website I can't add any new redirect in the admin. Error code:

```
Integrity constraint violation – [yii\db\IntegrityException](https://www.yiiframework.com/doc-2.0/yii-db-integrityexception.html)
SQLSTATE[23000]: Integrity constraint violation: 1216 Cannot add or update a child row: a foreign key constraint fails
The SQL being executed was: INSERT INTO `structureelements` (`structureId`, `dateCreated`, `dateUpdated`, `uid`, `lft`, `rgt`, `level`) VALUES (0, '2024-11-28 20:17:38', '2024-11-28 20:17:38', '80f2f836-76b9-4b32-af82-a81054235ec5', 1, 2, 0)
Error Info: Array
(
    [0] => 23000
    [1] => 1216
    [2] => Cannot add or update a child row: a foreign key constraint fails
```

### How to reproduce

I installed Sprout Redirects instead of Redirects Manager (disabling it). 

### Sprout Version

4.47.2

### Craft Version

4.13.3

### Database Type Version

MYSQL

**Comment by idleog** [comment]
I have the same issue. Locally it works, not on live site
CraftCMS: 5.5.3
Sprout Redirects Lite: 5.0.1
Database: MariaDB 10.6

**Comment by idleog** [comment]
**update**
I was playing around a little bit and here is what helped me:
Deinstalling and reinstalling the plugin on the live site made the bug disappear.

**But**
As soon as I deploy the project config files of local environment to the live site and apply them, the bug reappears.

Cheers
Peter

**Comment by mattfordham** [comment]
Same issue here, FWIW.

**Comment by robzor** [comment]
Does anyone have a fix for this?

**Comment by frontedbe** [comment]
bump

**Comment by angelokeirsebilck** [comment]
Bump, got same issue.

**Comment by BenParizek** [comment]
This is resolved in Sprout Redirects 5.0.2 and 4.47.3

**Comment by rhysmatthew** [comment]
@BenParizek running 5.0.3 and still getting this error. Unable to add redirects on our live site. 

![Image](https://github.com/user-attachments/assets/2292542d-d01c-4e36-98c2-dadd7b3ab56a)

**Comment by iamkeir** [comment]
Yep, running 5.0.3 and receiving same error on live, works fine locally. Uninstall/reinstall fixed - until next deployment...

**Comment by antcooper** [comment]
+1. We're having this issue too on a Craft instance running 5.8.17 and Redirect 5.0.3. The only way to avoid it was to ssh into the host and run the following. But we have to do this after each deploy for some reason.
```
 ./craft plugin/uninstall sprout-redirects
```
Followed by
```
./craft plugin/install sprout-redirects
```

**Comment by BenParizek** [comment]
I've added a new migration that should address this scenario.
